### ISSUE TITLE
LSP support

### ISSUE THREAD

**Issue by WeetHet** [zed-extensions/kotlin#1]
Zed has landed support for lsp-s in the preview, so could you add kotlin language server (https://github.com/fwcd/kotlin-language-server) support

**Comment by eth0net** [comment]
I'm working on Docker Compose support rn but happy to fork Kotlin and pick this one up after ^^

**Comment by maxdeviant** [comment]
> Hey thanks for reaching out, I'm not looking to maintain the Kotlin extension for Zed anymore and I'd be happy to let someone else take over, I've let the extension be available as there currently seem to be no other alternative.
> 
> I'm not sure how this would work, but if you're interested in maintaining it instead maybe githubs ownership transfer feature might work, or maybe you can fork this repository and i pr a removal of this one from the extensions repo?

@evrsen You could transfer the repo to the @zed-extensions org and we can add anyone who wants to help maintain it.

**Comment by maxdeviant** [comment]
> Sound good to me @maxdeviant , i tried transferring but got this error <img alt="Screenshot 2024-04-18 at 23 17 46" width="1412" src="https://private-user-images.githubusercontent.com/146845123/323763597-96b0ff41-a23d-4931-b7b3-baa087669404.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NzY3NTYsIm5iZiI6MTcxMzQ3NjQ1NiwicGF0aCI6Ii8xNDY4NDUxMjMvMzIzNzYzNTk3LTk2YjBmZjQxLWEyM2QtNDkzMS1iN2IzLWJhYTA4NzY2OTQwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQyMTQwNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNmY1YWVjNjg4NzA1MDEwNTllMmJjMmE4M2Y3NDNhNGFjNWI1NTg3MzBjMmY4NjU2MmJhYzg2ZDVhNzE3OTI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z9ibc2pxLGOSoXlgaZ-azdILPzrSIknFNxZMp4xSPWQ">

Ah, I see.

Could you try transferring it to me? And then I can transfer it into the organization.

**Comment by evrsen** [comment]
Done 👍

**Comment by cholwell** [comment]
Is anyone actively working on kotlin lsp support? If not I might

**Comment by henrik242** [comment]
@cholwell You can probably help out at https://github.com/zed-extensions/zed-kotlin

**Comment by cholwell** [comment]
@maxdeviant what is the difference between https://github.com/zed-industries/zed/tree/2ee257a5621d3c2714945e117d958383c14ae513/extensions and https://github.com/zed-extensions ?

**Comment by maxdeviant** [comment]
> @maxdeviant what is the difference between https://github.com/zed-industries/zed/tree/2ee257a5621d3c2714945e117d958383c14ae513/extensions and https://github.com/zed-extensions ?

The `extensions/` directory in the Zed repo is for languages that were previously built in to Zed that we extracted into extensions. We kept them in the Zed repo to make it easier to iterate on them. At some point they will likely move out into their own repositories.

The @zed-extensions org is for extensions that that are maintained (at least in part) by the Zed team. We will accept interested parties to help maintain them, though.

**Comment by cholwell** [comment]
So I made some progress:

- If I download and build the lsp from source and hardcode the command in extension it will run... however it wont highlight the majority of compliation errors ?
- Trying to get the extension to download from https://github.com/fwcd/kotlin-language-server/releases fails with 'failed to unzip _name_ archive' 

Will have another go at some point but if anyone wants to help, or has any insight on either point let me know.

**Comment by WeetHet** [comment]
> So I made some progress:
> 
>     * If I download and build the lsp from source and hardcode the command in extension it will run... however it wont highlight the majority of compliation errors ?
> 
>     * Trying to get the extension to download from https://github.com/fwcd/kotlin-language-server/releases fails with 'failed to unzip _name_ archive'
> 
> 
> Will have another go at some point but if anyone wants to help, or has any insight on either point let me know.

Could you show me the code you've written so far?

**Comment by cholwell** [comment]
https://github.com/cholwell/zed-kotlin/blob/main/src/kotlin.rs @WeetHet

**Comment by WeetHet** [comment]
> https://github.com/cholwell/zed-kotlin/blob/main/src/kotlin.rs @WeetHet

I not sure if I'm right, but in my extension, I download to the binary_path, not version_dir. Could you try that?

**Comment by cholwell** [comment]
@WeetHet I believe the whole installation zip is required due to it containing jar dependencies,

also I tried it and it fails with no such file or directory so not sure

**Comment by cholwell** [comment]
working https://github.com/zed-extensions/zed-kotlin/pull/8

**Comment by cholwell** [comment]
@WeetHet please can you close issue now PR is merged

**Comment by maxdeviant** [comment]
Language server support is available now in v0.0.3 of the Kotlin extension.

**Comment by FalconSlayer51** [comment]
Hey @maxdeviant you said lsp support added, but its not working.

**Comment by FalconSlayer51** [comment]
Hello @maxdeviant i fixed the issue with lsp not working in windows, and it working fine in windows
![image](https://github.com/user-attachments/assets/b18b986b-b139-477e-b39c-424e50d803dd)

**Comment by FalconSlayer51** [comment]
@spaceunifyfifty yeah ive done that its now fixed with #16
