### ISSUE TITLE
`hightlights.scm` failing to highlight many keywords, inconsistent with other language implementations 

### ISSUE THREAD

**Issue by spaceunifyfifty** [zed-extensions/kotlin#6]
The extension currently does not highlight keywords `if`,`else`,`when`,`for`,`while`,`do`,`try`,`catch`,`throw`,`finally` properly.
<img width="543" alt="image" src="https://github.com/zed-extensions/zed-kotlin/assets/158013953/21681840-20d5-4574-933a-fd6dc06bcd20">

I have found this can be fixed by modifying the [highlights.scm](https://github.com/zed-extensions/zed-kotlin/blob/main/languages/kotlin/highlights.scm).

First, I noticed that the highlights.scm does not classify them as `@keyword`, but instead their own distinct classifications `@conditional`, `@repeat`, `@exception`
```scm
[
	"val"
	"var"
	"enum"
	"class"
	"object"
	"interface"
;	"typeof" ; NOTE: It is reserved for future use
] @keyword

("fun") @keyword.function

(jump_expression) @keyword.return

[
	"if"
	"else"
	"when"
] @conditional

[
	"for"
	"do"
	"while"
] @repeat

[
	"try"
	"catch"
	"throw"
	"finally"
] @exception
```

while the [highlights.scm](https://github.com/zed-industries/zed/blob/f60bebb93ba9cce6e17949450cdba56a1e14dc7c/crates/zed/src/languages/typescript/highlights.scm) for TypeScript has all of them in the `@keyword` list and lacks `@conditional`,`@repeat`,`@exception` classification's entirely.
```scm
[
  "as"
  "async"
  "await"
  "break"
  "case"
  "catch"
  "class"
  "const"
  "continue"
  "debugger"
  "default"
  "delete"
  "do"
  "else"
  "export"
  "extends"
  "finally"
  "for"
  "from"
  "function"
  "get"
  "if"
  "import"
  "in"
  "instanceof"
  "let"
  "new"
  "of"
  "return"
  "satisfies"
  "set"
  "static"
  "switch"
  "target"
  "throw"
  "try"
  "typeof"
  "var"
  "void"
  "while"
  "with"
  "yield"
] @keyword
```

I have tested locally and found that if you add the tokens into the `@keyword` list ***and*** remove them from the `@conditional`,`@repeat`,`@exception` lists (and so removing those classifications entirely), syntax highlighting works.

<img width="543" alt="image" src="https://github.com/zed-extensions/zed-kotlin/assets/158013953/54b73ad6-7b02-440d-a5bd-ef0a07375154">
 
This makes me suspect that the scheme file was incorrectly written, or that it relies on other parts of the extension that are not yet making use of the `@conditional`,`@repeat`,`@exception` identifiers. Why is it inconsistent with TypeScript's implementation?

**Comment by evrsen** [comment]
Hi, I take responsibility for this, I copied the scheme code from https://github.com/fwcd/tree-sitter-kotlin/tree/main/queries
